### ISSUE TITLE
Able to enable/disable mods in game

### ISSUE THREAD

**Issue by hacktic-dev** [FujiAPI/Fuji#14]

**Comment by jasminegamedev** [comment]
This was implemented as part of the new mod menu in this commit:
https://github.com/FujiAPI/Fuji/commit/7d4521c713e5479f7a9120685f80562642b20abc
There will likely be some additional work needed to support this when we set up mod dependencies, and also possibly when we add monomod support, but I think that can be handled as part of those issues.
