### ISSUE TITLE
Better support for custom entities implemented by mods in TB

### ISSUE THREAD

**Issue by axiand** [FujiAPI/Fuji#22]
Here's something I've thought up of to make the mapper experience smoother when dealing with multiple entity-implementing dependencies:

- Mods would be able to use a few utility functions to extend custom entities with metadata.
- Running Fuji with a special command line flag (e.g. `--generate-fgd="mod-folder-name"`) uses this metadata to merge together a new `fgd` file, including all entities implemented by the mod's dependencies. Outputs it to the mod root directory.
- - Alternatively this can be done with a button somewhere ingame?
- Later, when adding new dependencies, they'd repeat the same steps.

I would add this to the 1.0.0 checklist but I'm not sure if we want to keep this as a long-term goal /shrug

**Comment by Gingeh** [comment]
I'd suggest that it might be simpler for mods to just include a `.fgd` file in their folder.
I would prefer a command-line flag over something in-game, but a separate script might be even better (to keep dev tools separate from the game itself)

**Comment by axiand** [comment]
Gonna set this as a goal for 0.5.0. Up for debate

**Comment by jasminegamedev** [comment]
I sort of had a workaround solution for this I posted in the discord a while ago. I was thinking of possibly cleaning it up and publishing it, but I don't know if I would want it to be part of fuji itself. We might want to make a new modding tools repo or something for that kind of stuff.

**Comment by axiand** [comment]
This is better suited for the modding tools repo

**Comment by jasminegamedev** [comment]
I have set up a tool for this inside of a new Fuji Modding Resources repo.
https://github.com/FujiAPI/Fuji-Modding-Resources
This repo is still fairly basic, and might get some cleanup in the future, but the tool itself is now available.
