### ISSUE TITLE
Implement debug ui support via ImGui

### ISSUE THREAD

**Issue by hacktic-dev** [FujiAPI/Fuji#28]
It would be great to provide a standard set up debug variables that can be viewed in game with imgui to aid with development. Optionally mods can also display their own variables via an interface.

**Comment by hacktic-dev** [comment]
This is already implemented in the TAS so have a look how it works there: https://github.com/psyGamer/Celeste64-TAS

**Comment by jasminegamedev** [comment]
This should be possible now via the changes in https://github.com/FujiAPI/Fuji/pull/37
Closing this ticket, but we can reopen if there are issues.
