### ISSUE TITLE
mods cannot use external dependencies

### ISSUE THREAD

**Issue by bananaturtlesandwich** [FujiAPI/Fuji#34]
trying to use a nuget package or any other package not used by the game results in a crash

**Comment by jasminegamedev** [comment]
can you share information from your log about what the error from the crash looks like?

**Comment by axiand** [comment]
Pretty sure this was resolved over in Discord? Feel free to reopen if it's not

**Comment by jasminegamedev** [comment]
I don't think this is resolved yet. I think this is what this pr is trying to acchieve, so it should be possible when this is done and merged:
https://github.com/FujiAPI/Fuji/pull/46

**Comment by bananaturtlesandwich** [comment]
yep @jasminegamedev is correct that's what the pr is doing

**Comment by jasminegamedev** [comment]
I believe this should be fixed now that this PR is merged.
https://github.com/FujiAPI/Fuji/pull/46
If it is not fixed, let me know, and we can reopen.
