### ISSUE TITLE
Mod Languages all get put into the same static Dictionary

### ISSUE THREAD

**Issue by NoelFB** [FujiAPI/Fuji#35]
If you have a Mod that adds a new language, all text ends up going into `GameMode.Strings` and `GameMode.Dialog`, regardless of language. These dictionaries need to be another level deep and account for Language, ex:

```cs
Dictionary<string, Dictionary<string, string>> Strings
```

Where the top-level dictionary is the Language.ID, I think.

You can test this issue by simply copying English.json and changing the copied file ID to something else (ex. `"ID": "spanish"`).

**Comment by jasminegamedev** [comment]
Ahh, good catch. I have fixed and resolved this in this commit:
https://github.com/ExOK/Celeste64/commit/3a42427df8511621d3e0635e86307d5edbdca8ea
While working on this, I also noticed a few things that I think were issues from the upstream. I fixed them in my commit, but I made a separate commit to apply them to the upstream, and made a pull request for that

https://github.com/ExOK/Celeste64/pull/73

**Comment by jasminegamedev** [comment]
Marking as closed, since I believe this is fixed now.
