### ISSUE TITLE
Add Fuji Option to write to logs

### ISSUE THREAD

**Issue by jasminegamedev** [FujiAPI/Fuji#47]
Currently, the game will only write to a log file if the game crashes from an exception being thrown.
It might be useful for us to add an option that lets people turn on more regular non-error logging as well. This could be useful for us for troubleshooting issues people see, and also could be useful for modders to debug their own mods.

**Comment by axiand** [comment]
Adding onto this: an option to run Fuji along with a console window would be nice. Maybe with a command line flag like `--console`

**Comment by jasminegamedev** [comment]
I added the main part of this to log to a file in https://github.com/FujiAPI/Fuji/commit/57f9c92619acb03a1b5cafa564f9bb103c88dc2e
Opening a console along side it is a bit more complicated, so I decided to leave that as a separate commit.

**Comment by jasminegamedev** [comment]
I Implemented the ability to open the application with a console by passing a "--console" argument in https://github.com/FujiAPI/Fuji/commit/a6787bfa7b9a58602875f2e034625456576a7d70
With that and the previous commit, I think this issue should be resolved.
