### ISSUE TITLE
Implement ModInfo metadata files and Asset Replacements

### ISSUE THREAD

**Issue by jasminegamedev** [FujiAPI/Fuji#5]
We would like a way for modders to specify assets to replace a base game asset.
This will likely be managed through a new ModInfo.json file

**Comment by axiand** [comment]
We'd definitely benefit from an `everest.yaml` equivalent. I propose a similar structure to what Everest does, which would make it easier for anyone with Celeste modding experience. Something like

```json
{
    "id": "<unique mod id>",
    "name": "<human-friendly mod name>",
    "version": "<semver>",
    "dependencies": [ {
        "id": "<mod id>",
        "version": "<minimum required ver>"
    }, { ... } ],
    "assetReplacements": {
        "<vanilla asset path>": "<mod asset path>"
    }
}
```
etc.

**Comment by hacktic-dev** [comment]
This can be closed now, right?

**Comment by jasminegamedev** [comment]
This is done as of 
https://github.com/FujiAPI/Fuji/pull/12
