### ISSUE TITLE
Graceful mod loader error handling

### ISSUE THREAD

**Issue by axiand** [FujiAPI/Fuji#50]
- [x] Don't crash the game if `Fuji.json` is missing.
- [ ] Display a user-friendly error message if a mod fails to load. Should not interrupt gameplay or force the game to be restarted.
- [x] Enforce unique mod IDs.

**Comment by jasminegamedev** [comment]
Note: We should wait until https://github.com/FujiAPI/Fuji/pull/46 is merged to start this, because it moves all the relevant files around.

**Comment by jasminegamedev** [comment]
I took care of the first and third parts of this in https://github.com/FujiAPI/Fuji/commit/e20ea904c634df719192face5c0e8248c6ddccf7, so now it properly enforces mods be unique, and it no longer crashes like it was doing before. 
Currently, it will just log the error to the log file, but if we want it to show the error on screen, I think we should handle that as a separate commit.

**Comment by jasminegamedev** [comment]
Finished in https://github.com/FujiAPI/Fuji/commit/5bb0240d9ac9096161aade5346cfb6498ad429ca. I added an on screen warning on overworld screen when mods failed to load plus I added a popup with more specific details when opening the mod menu.
