### ISSUE TITLE
Debug Map Switcher

### ISSUE THREAD

**Issue by axiand** [FujiAPI/Fuji#51]
Think Everest's debug map. Pressing F6 opens a menu where the player can instantly warp to any map in the current mod. Will likely need to do #45 as a prerequisite

**Comment by jasminegamedev** [comment]
I have an alternative idea that might get rid of the prerequisite, and might give us more long term control over this. We could maybe consider using imgui as the base for a debug menu instead of the in game UI tools.

**Comment by jasminegamedev** [comment]
I implemented a version of this in https://github.com/FujiAPI/Fuji/commit/9f1cabb3ab93060a9ffd76a46e82b60b15d29ba9
I ended up using imgui like I mentioned. I also added a few other debug options including the ability to change  to another map, in the current mod, the ability to teleport to a checkpoint in the current map, an option to kill the player, an option to refill double dash, and an option to enter a version of the debug fly/noclip mode I was showing off a few weeks ago. I figure we can expand this with any more debug commands we want to add in the future.
To enter the menu, you first have to enable it in the fuji options. I did this so people only do it if they know what they're doing, and also maybe to discourage people from using it to cheat too much.
Then once it's enabled you can press F6 to toggle the debug menu to be open or closed. I'm not particularly attached to F6, so we can change that to something else if we'd like.
