### ISSUE TITLE
Rebind controls ingame

### ISSUE THREAD

**Issue by axiand** [FujiAPI/Fuji#52]
`Pause > Options > Controls`. Could allow multiple binds per entry, must allow at least 1 controller bind and 1 keyboard bind.

**Comment by psyGamer** [comment]
Related upstream issue, which has already a bit of progress: ExOK/Celeste64#63

**Comment by axiand** [comment]
Moved to 0.7 blockers along with #29

**Comment by axiand** [comment]
Linked this to #81

**Comment by jasminegamedev** [comment]
Resolved in https://github.com/FujiAPI/Fuji/pull/81
